import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ShowNavigation from "@/components/layouts/navigation/ShowNavigation";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { SocketProvider } from "@/context/SocketProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  ${inter.className}  antialiased bg-background-secondary`}
      >
        <Suspense
          fallback={
            <div className="w-full h-screen flex items-center justify-center">
              <span className="font-bold text-5xl ">Prosongo</span>
            </div>
          }
        >
          <ReactQueryProvider>
            <SocketProvider>
              {/* Navigation এখন শর্ত অনুযায়ী show/hide হবে */}
              <ShowNavigation />

              {children}
            </SocketProvider>
          </ReactQueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
